// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

type StringSlice []string

func (s *StringSlice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("[%s]", strings.Join(*s, ", "))
}

func (s *StringSlice) Set(value string) error {
	*s = append(*s, value)
	return nil
}

type IntSlice []int

func (s *IntSlice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *IntSlice) Set(value string) error {
	i, err := strconv.Atoi(value)
	if err != nil {
		return err
	}
	*s = append(*s, i)
	return nil
}

type Int64Slice []int64

func (s *Int64Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Int64Slice) Set(value string) error {
	i, err := strconv.ParseInt(value, 10, 64)
	if err != nil {
		return err
	}
	*s = append(*s, i)
	return nil
}

type Int32Slice []int32

func (s *Int32Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Int32Slice) Set(value string) error {
	i, err := strconv.ParseInt(value, 10, 32)
	if err != nil {
		return err
	}
	*s = append(*s, int32(i))
	return nil
}

type Int16Slice []int16

func (s *Int16Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Int16Slice) Set(value string) error {
	i, err := strconv.ParseInt(value, 10, 16)
	if err != nil {
		return err
	}
	*s = append(*s, int16(i))
	return nil
}

type Int8Slice []int8

func (s *Int8Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Int8Slice) Set(value string) error {
	i, err := strconv.ParseInt(value, 10, 8)
	if err != nil {
		return err
	}
	*s = append(*s, int8(i))
	return nil
}

type UintSlice []uint

func (s *UintSlice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *UintSlice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, strconv.IntSize) // uint can be 32 or 64 bit, but 64 covers both
	if err != nil {
		return err
	}
	*s = append(*s, uint(i))
	return nil
}

type Uint64Slice []uint64

func (s *Uint64Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Uint64Slice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, 64)
	if err != nil {
		return err
	}
	*s = append(*s, i)
	return nil
}

type Uint32Slice []uint32

func (s *Uint32Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Uint32Slice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, 32)
	if err != nil {
		return err
	}
	*s = append(*s, uint32(i))
	return nil
}

type Uint16Slice []uint16

func (s *Uint16Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Uint16Slice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, 16)
	if err != nil {
		return err
	}
	*s = append(*s, uint16(i))
	return nil
}

type Uint8Slice []uint8

func (s *Uint8Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Uint8Slice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, 8)
	if err != nil {
		return err
	}
	*s = append(*s, uint8(i))
	return nil
}

type Float64Slice []float64

func (s *Float64Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Float64Slice) Set(value string) error {
	f, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return err
	}
	*s = append(*s, f)
	return nil
}

type Float32Slice []float32

func (s *Float32Slice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *Float32Slice) Set(value string) error {
	f, err := strconv.ParseFloat(value, 32)
	if err != nil {
		return err
	}
	*s = append(*s, float32(f))
	return nil
}

type BoolSlice []bool

func (s *BoolSlice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *BoolSlice) Set(value string) error {
	b, err := strconv.ParseBool(value)
	if err != nil {
		return err
	}
	*s = append(*s, b)
	return nil
}

func (s *BoolSlice) IsBoolFlag() bool {
	return true
}

type DurationSlice []time.Duration

func (s *DurationSlice) String() string {
	if s == nil {
		return "[]"
	}
	return fmt.Sprintf("%v", *s)
}

func (s *DurationSlice) Set(value string) error {
	d, err := time.ParseDuration(value)
	if err != nil {
		return err
	}
	*s = append(*s, d)
	return nil
}

type StringPointerSlice []*string

func (s *StringPointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, *p)
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *StringPointerSlice) Set(value string) error {
	val := value
	*s = append(*s, &val)
	return nil
}

type IntPointerSlice []*int

func (s *IntPointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *IntPointerSlice) Set(value string) error {
	i, err := strconv.Atoi(value)
	if err != nil {
		return err
	}
	*s = append(*s, &i)
	return nil
}

type Int64PointerSlice []*int64

func (s *Int64PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Int64PointerSlice) Set(value string) error {
	i, err := strconv.ParseInt(value, 10, 64)
	if err != nil {
		return err
	}
	*s = append(*s, &i)
	return nil
}

type Int32PointerSlice []*int32

func (s *Int32PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Int32PointerSlice) Set(value string) error {
	i, err := strconv.ParseInt(value, 10, 32)
	if err != nil {
		return err
	}
	v := int32(i)
	*s = append(*s, &v)
	return nil
}

type Int16PointerSlice []*int16

func (s *Int16PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Int16PointerSlice) Set(value string) error {
	i, err := strconv.ParseInt(value, 10, 16)
	if err != nil {
		return err
	}
	v := int16(i)
	*s = append(*s, &v)
	return nil
}

type Int8PointerSlice []*int8

func (s *Int8PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Int8PointerSlice) Set(value string) error {
	i, err := strconv.ParseInt(value, 10, 8)
	if err != nil {
		return err
	}
	v := int8(i)
	*s = append(*s, &v)
	return nil
}

type UintPointerSlice []*uint

func (s *UintPointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *UintPointerSlice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, strconv.IntSize)
	if err != nil {
		return err
	}
	v := uint(i)
	*s = append(*s, &v)
	return nil
}

type Uint64PointerSlice []*uint64

func (s *Uint64PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Uint64PointerSlice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, 64)
	if err != nil {
		return err
	}
	*s = append(*s, &i)
	return nil
}

type Uint32PointerSlice []*uint32

func (s *Uint32PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Uint32PointerSlice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, 32)
	if err != nil {
		return err
	}
	v := uint32(i)
	*s = append(*s, &v)
	return nil
}

type Uint16PointerSlice []*uint16

func (s *Uint16PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Uint16PointerSlice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, 16)
	if err != nil {
		return err
	}
	v := uint16(i)
	*s = append(*s, &v)
	return nil
}

type Uint8PointerSlice []*uint8

func (s *Uint8PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%d", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Uint8PointerSlice) Set(value string) error {
	i, err := strconv.ParseUint(value, 10, 8)
	if err != nil {
		return err
	}
	v := uint8(i)
	*s = append(*s, &v)
	return nil
}

type Float64PointerSlice []*float64

func (s *Float64PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%v", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Float64PointerSlice) Set(value string) error {
	f, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return err
	}
	*s = append(*s, &f)
	return nil
}

type Float32PointerSlice []*float32

func (s *Float32PointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%v", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *Float32PointerSlice) Set(value string) error {
	f, err := strconv.ParseFloat(value, 32)
	if err != nil {
		return err
	}
	v := float32(f)
	*s = append(*s, &v)
	return nil
}

type BoolPointerSlice []*bool

func (s *BoolPointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%v", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *BoolPointerSlice) Set(value string) error {
	b, err := strconv.ParseBool(value)
	if err != nil {
		return err
	}
	*s = append(*s, &b)
	return nil
}

func (s *BoolPointerSlice) IsBoolFlag() bool {
	return true
}

type DurationPointerSlice []*time.Duration

func (s *DurationPointerSlice) String() string {
	if s == nil {
		return "[]"
	}
	var parts []string
	for _, p := range *s {
		if p != nil {
			parts = append(parts, fmt.Sprintf("%v", *p))
		} else {
			parts = append(parts, "<nil>")
		}
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func (s *DurationPointerSlice) Set(value string) error {
	d, err := time.ParseDuration(value)
	if err != nil {
		return err
	}
	*s = append(*s, &d)
	return nil
}
