// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestGenerate_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewGenerate()

	called := false
	cmd.CommandAction = func(c *Generate) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--width")
	args = append(args, "1")
	args = append(args, "--height")
	args = append(args, "1")
	args = append(args, "--themedir")
	args = append(args, "test")
	args = append(args, "--font")
	args = append(args, "test")
	args = append(args, "--dpi")
	args = append(args, "test")
	args = append(args, "--size")
	args = append(args, "test")
	args = append(args, "--text")
	args = append(args, "test")
	args = append(args, "--out")
	args = append(args, "test")
	args = append(args, "--chevron")
	args = append(args, "test")
	args = append(args, "--avatar-pos")
	args = append(args, "test")
	args = append(args, "--avatar-scale")
	args = append(args, "test")
	args = append(args, "--animation")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.width != 1 {
		t.Errorf("Expected width to be 1, got '%v'", cmd.width)
	}
	if cmd.height != 1 {
		t.Errorf("Expected height to be 1, got '%v'", cmd.height)
	}
	if cmd.themeDir != "test" {
		t.Errorf("Expected themeDir to be 'test', got '%v'", cmd.themeDir)
	}
	if cmd.fontName != "test" {
		t.Errorf("Expected fontName to be 'test', got '%v'", cmd.fontName)
	}
	if cmd.dpi != "test" {
		t.Errorf("Expected dpi to be 'test', got '%v'", cmd.dpi)
	}
	if cmd.fontSize != "test" {
		t.Errorf("Expected fontSize to be 'test', got '%v'", cmd.fontSize)
	}
	if cmd.textSource != "test" {
		t.Errorf("Expected textSource to be 'test', got '%v'", cmd.textSource)
	}
	if cmd.outPrefix != "test" {
		t.Errorf("Expected outPrefix to be 'test', got '%v'", cmd.outPrefix)
	}
	if cmd.chevronLoc != "test" {
		t.Errorf("Expected chevronLoc to be 'test', got '%v'", cmd.chevronLoc)
	}
	if cmd.avatarPos != "test" {
		t.Errorf("Expected avatarPos to be 'test', got '%v'", cmd.avatarPos)
	}
	if cmd.avatarScale != "test" {
		t.Errorf("Expected avatarScale to be 'test', got '%v'", cmd.avatarScale)
	}
	if cmd.animation != "test" {
		t.Errorf("Expected animation to be 'test', got '%v'", cmd.animation)
	}
}

func TestGenerate_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewGenerate()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
