// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/golang-rpg-textbox/cli"
)

var _ Cmd = (*Generate)(nil)

type Generate struct {
	*RootCmd
	Flags       *flag.FlagSet
	width       int
	height      int
	themeDir    string
	fontName    string
	dpi         string
	fontSize    string
	textSource  string
	outPrefix   string
	chevronLoc  string
	avatarPos   string
	avatarScale string
	animation   string
	SubCommands map[string]Cmd
}

type UsageDataGenerate struct {
	*Generate
	Recursive bool
}

func (c *Generate) Usage() {
	err := executeUsage(os.Stderr, "generate_usage.txt", UsageDataGenerate{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Generate) UsageRecursive() {
	err := executeUsage(os.Stderr, "generate_usage.txt", UsageDataGenerate{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Generate) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "width":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.width = iv

			case "height":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.height = iv

			case "themeDir", "themedir":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.themeDir = value

			case "fontName", "font":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.fontName = value

			case "dpi":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.dpi = value

			case "fontSize", "size":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.fontSize = value

			case "textSource", "text":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.textSource = value

			case "outPrefix", "out":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.outPrefix = value

			case "chevronLoc", "chevron":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.chevronLoc = value

			case "avatarPos", "avatar-pos":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.avatarPos = value

			case "avatarScale", "avatar-scale":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.avatarScale = value

			case "animation":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.animation = value
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if err := cli.GenerateTextBox(c.width, c.height, c.themeDir, c.fontName, c.dpi, c.fontSize, c.textSource, c.outPrefix, c.chevronLoc, c.avatarPos, c.avatarScale, c.animation); err != nil {
		return fmt.Errorf("generate failed: %w", err)
	}

	return nil
}

func (c *RootCmd) NewGenerate() *Generate {
	set := flag.NewFlagSet("generate", flag.ContinueOnError)
	v := &Generate{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.IntVar(&v.width, "width", 600, "Doc width")

	set.IntVar(&v.height, "height", 150, "Doc height")

	set.StringVar(&v.themeDir, "themedir", "./theme", "Directory to find the theme")

	set.StringVar(&v.fontName, "font", "goregular", "Text font")

	set.StringVar(&v.dpi, "dpi", "75", "Doc dpi")

	set.StringVar(&v.fontSize, "size", "16", "font size")

	set.StringVar(&v.textSource, "text", "", "File in or - for std input")

	set.StringVar(&v.outPrefix, "out", "out-", "Prefix of filename to output")

	set.StringVar(&v.chevronLoc, "chevron", "", "Use help for list")

	set.StringVar(&v.avatarPos, "avatar-pos", "", "Use help for list")

	set.StringVar(&v.avatarScale, "avatar-scale", "", "Use help for list")

	set.StringVar(&v.animation, "animation", "", "Use help for list")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
