// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestSamplesAnimation_Execute(t *testing.T) {

	parent := &Samples{}
	parent.RootCmd = &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewSamplesAnimation()

	called := false
	cmd.CommandAction = func(c *SamplesAnimation) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--width")
	args = append(args, "1")
	args = append(args, "--height")
	args = append(args, "1")
	args = append(args, "--text")
	args = append(args, "test")
	args = append(args, "--outdir")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.width != 1 {
		t.Errorf("Expected width to be 1, got '%v'", cmd.width)
	}
	if cmd.height != 1 {
		t.Errorf("Expected height to be 1, got '%v'", cmd.height)
	}
	if cmd.textSource != "test" {
		t.Errorf("Expected textSource to be 'test', got '%v'", cmd.textSource)
	}
	if cmd.outDir != "test" {
		t.Errorf("Expected outDir to be 'test', got '%v'", cmd.outDir)
	}
}

func TestSamplesAnimation_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &Samples{}
	parent.RootCmd = &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewSamplesAnimation()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
