// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"errors"

	"github.com/arran4/golang-rpg-textbox/cli"
	"github.com/arran4/golang-rpg-textbox/cmd"
)

var _ Cmd = (*SamplesStatic)(nil)

type SamplesStatic struct {
	*Samples
	Flags         *flag.FlagSet
	width         int
	height        int
	textSource    string
	outDir        string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *SamplesStatic) error
}

type UsageDataSamplesStatic struct {
	*SamplesStatic
	Recursive bool
}

func (c *SamplesStatic) Usage() {
	err := executeUsage(os.Stderr, "static_usage.txt", UsageDataSamplesStatic{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *SamplesStatic) UsageRecursive() {
	err := executeUsage(os.Stderr, "static_usage.txt", UsageDataSamplesStatic{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *SamplesStatic) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "width":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				v, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.width = v

			case "height":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				v, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.height = v

			case "textSource", "text":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.textSource = value

			case "outDir", "outdir":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.outDir = value
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("static failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *Samples) NewSamplesStatic() *SamplesStatic {
	set := flag.NewFlagSet("static", flag.ContinueOnError)
	v := &SamplesStatic{
		Samples:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.IntVar(&v.width, "width", 600, "Doc width")

	set.IntVar(&v.height, "height", 150, "Doc height")

	set.StringVar(&v.textSource, "text", "", "File in, or - for std input")

	set.StringVar(&v.outDir, "outdir", "images/", "directory to save samples to")
	set.Usage = v.Usage

	v.CommandAction = func(c *SamplesStatic) error {

		err := cli.GenerateSamples(c.width, c.height, c.textSource, c.outDir)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("static failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
