// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"testing"
)

func TestSamples_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewSamples()

	args := []string{}

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
}
