// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestSamples_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewSamples()

	args := []string{}

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

}

func TestSamples_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewSamples()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
