// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"testing"
)

func TestStatic_Execute(t *testing.T) {

	parent := &Samples{}
	cmd := parent.NewStatic()

	called := false
	cmd.CommandAction = func(c *Static) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--width")
	args = append(args, "1")
	args = append(args, "--height")
	args = append(args, "1")
	args = append(args, "--textSource")
	args = append(args, "test")
	args = append(args, "--outDir")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.width != 1 {
		t.Errorf("Expected width to be 1, got '%v'", cmd.width)
	}
	if cmd.height != 1 {
		t.Errorf("Expected height to be 1, got '%v'", cmd.height)
	}
	if cmd.textSource != "test" {
		t.Errorf("Expected textSource to be 'test', got '%v'", cmd.textSource)
	}
	if cmd.outDir != "test" {
		t.Errorf("Expected outDir to be 'test', got '%v'", cmd.outDir)
	}
}
