// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"testing"
)

func TestStatic_Execute(t *testing.T) {

	parent := &Samples{}
	cmd := parent.NewStatic()

	called := false
	cmd.CommandAction = func(c *Static) error {
		called = true
		return nil
	}

	args := []string{}

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}
}
