// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/golang-rpg-textbox/cli"
)

var _ Cmd = (*Static)(nil)

type Static struct {
	*Samples
	Flags       *flag.FlagSet
	width       int
	height      int
	textSource  string
	outDir      string
	SubCommands map[string]Cmd
}

type UsageDataStatic struct {
	*Static
	Recursive bool
}

func (c *Static) Usage() {
	err := executeUsage(os.Stderr, "static_usage.txt", UsageDataStatic{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Static) UsageRecursive() {
	err := executeUsage(os.Stderr, "static_usage.txt", UsageDataStatic{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Static) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "width":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.width = iv

			case "height":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.height = iv

			case "textSource", "text":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.textSource = value

			case "outDir", "outdir":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.outDir = value
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if err := cli.GenerateSamples(c.width, c.height, c.textSource, c.outDir); err != nil {
		return fmt.Errorf("static failed: %w", err)
	}

	return nil
}

func (c *Samples) NewStatic() *Static {
	set := flag.NewFlagSet("static", flag.ContinueOnError)
	v := &Static{
		Samples:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.IntVar(&v.width, "width", 600, "Doc width")

	set.IntVar(&v.height, "height", 150, "Doc height")

	set.StringVar(&v.textSource, "text", "", "File in or - for std input")

	set.StringVar(&v.outDir, "outdir", "images/", "directory to save samples to")
	set.Usage = v.Usage

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
