project_name: golang-rpg-textbox
builds:
  -
    id: "rpgtextbox"
    binary: "rpgtextbox"
    dir: cmd/rpgtextbox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Ubels Software Development
    homepage: https://github.com/arran4/golang-rpg-textbox
    maintainer: Arran Ubels <arran@ubels.com.au>
    description: RPG Textbox Generator
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
