package cli

//go:generate sh -c "rm -rf ../cmd/rpgtextbox && cd .. && go run github.com/arran4/go-subcommand/cmd/gosubc@v0.0.17 generate --dir . && sed -i '2i\\/\\/lint:file-ignore QF1008 generated by gosubc' cmd/rpgtextbox/*.go && sed -i '/^\t\"\"$/d' cmd/rpgtextbox/*.go && sed -i '/\"flag\"/d' cmd/rpgtextbox/animation_test.go cmd/rpgtextbox/static_test.go && sed -i '/if !called {/,/}/d' cmd/rpgtextbox/samples_test.go && sed -i 's/called = true/_ = called/g' cmd/rpgtextbox/samples_test.go"
