package cli

//go:generate sh -c "rm -rf ../cmd/rpgtextbox && cd .. && go run github.com/arran4/go-subcommand/cmd/gosubc@v0.0.17 generate --dir . && perl -pi -e 'print \"//lint:file-ignore QF1008 generated by gosubc\\n\" if \$. == 2; print \"//lint:file-ignore SA4006 generated by gosubc\\n\" if \$. == 2; s/^\\t\\\"\\\"\\n//g; close ARGV if eof;' cmd/rpgtextbox/*.go && rm -f cmd/rpgtextbox/samples_test.go && go run golang.org/x/tools/cmd/goimports@latest -w cmd/rpgtextbox/"
